# Generated by Django 4.0.3 on 2022-04-05 07:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок Title')),
                ('description', models.CharField(max_length=350, verbose_name='Заголовок Description')),
                ('h1', models.CharField(max_length=255, verbose_name='Заголовок H1')),
                ('image_zast', models.ImageField(upload_to='cat/image', verbose_name='Заставка категории')),
                ('post', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('introtext', models.CharField(max_length=1000, verbose_name='Краткое описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
