# Generated by Django 4.0.3 on 2022-04-05 08:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=350, verbose_name='Заголовок Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_zast',
            field=models.ImageField(blank=True, upload_to='cat/image', verbose_name='Заставка категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='introtext',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание'),
        ),
    ]
