# Generated by Django 4.0.3 on 2022-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_remove_category_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='introtext',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='introtext',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Краткое описание'),
        ),
    ]
