# Generated by Django 4.0.3 on 2022-04-05 09:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_created_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URl'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок Title')),
                ('description', models.CharField(blank=True, max_length=350, verbose_name='Заголовок Description')),
                ('h1', models.CharField(max_length=255, verbose_name='Заголовок H1')),
                ('image_zast', models.ImageField(blank=True, upload_to='cat/image', verbose_name='Заставка статьи')),
                ('post', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание')),
                ('introtext', models.CharField(blank=True, max_length=1000, verbose_name='Краткое описание')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('url', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URl')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
                'ordering': ('title',),
            },
        ),
    ]
