# Generated by Django 4.0.3 on 2022-04-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_introtext_alter_news_introtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='blog.category', verbose_name='Категория'),
        ),
    ]
