# Generated by Django 4.0.3 on 2022-04-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_news_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='blog.category', verbose_name='Категория'),
        ),
    ]
