# Generated by Django 4.0.3 on 2022-04-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_news_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_zast',
            field=models.ImageField(blank=True, upload_to='cat/%Y-%m-%d/', verbose_name='Заставка категории'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_zast',
            field=models.ImageField(blank=True, upload_to='post/%Y-%m-%d/', verbose_name='Заставка статьи'),
        ),
    ]
