# Generated by Django 4.0.3 on 2022-04-08 08:50

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_image_zast_alter_news_image_zast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_zast',
            field=models.ImageField(blank=True, upload_to=blog.models.get_file_path_category, verbose_name='Заставка категории'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_zast',
            field=models.ImageField(blank=True, upload_to=blog.models.get_file_path_news, verbose_name='Заставка статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='blog.category', verbose_name='Категория'),
        ),
    ]
