# Generated by Django 4.0.3 on 2022-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_birthday_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
