# Generated by Django 4.0.3 on 2022-04-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_phone',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
